# Generated by Django 2.1 on 2018-11-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now_add=True)),
                ('last_check', models.DateTimeField(auto_now_add=True)),
                ('site_link', models.URLField(default='url', max_length=250, unique=True)),
                ('title', models.CharField(default='Site name', max_length=25, unique=True)),
                ('description', models.TextField(default='Short description', max_length=144)),
                ('type', models.IntegerField(choices=[(1, 'Un define'), (2, 'Tool'), (3, 'Aviation'), (4, 'Interesting'), (5, 'Motorcycle'), (6, 'Programation')], default=1)),
            ],
        ),
    ]
