"""
Django settings for Bookmarks project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

# load correct settings file depending of the Os

import platform

if platform.system() == 'Windows':
    from .settings_file.settings_local import *
else:
    from .settings_file.settings_production import *

