"""
Django settings for Bookmarks project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

# load correct settings file depending of the Os

import platform

from dotenv import load_dotenv, find_dotenv

if platform.system() == 'Windows':

    from .settings_file.settings_local import *

else:
    try:
        import RPi.GPIO as gpio
        # Following ling change to match path to .env.PI on the Raspberry PI
        load_dotenv(find_dotenv('PI.env'))
        from .settings_file.settings_PI import *
    except(ImportError, RuntimeError):

        # Following ling change to match path to .env.production on the server
        find_dotenv(find_dotenv('Production.env'))
        from .settings_file.settings_production import *

